name: On Push

on: push

jobs:
  sync-discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - name: sync discussions
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GISCUS_REPO: smeijer/blog-comments
          GISCUS_REPO_ID: R_kgDOLwktSA
          GISCUS_CATEGORY: Announcements
          GISCUS_CATEGORY_ID: DIC_kwDOLwktSM4Ceznj
        run: ./node_modules/.bin/tsx ./scripts/to-discussions.ts
